# Generated by Django 5.2.3 on 2025-07-03 16:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorados', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Navigator',
            new_name='Navigators',
        ),
    ]
