# Generated by Django 5.2.3 on 2025-07-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorados', '0002_rename_navigator_navigators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorados',
            name='estagio',
            field=models.CharField(choices=[('E1', '10-100k'), ('E2', '100-1kk')], max_length=2),
        ),
    ]
